version: "3"
services:
  mongodb:
    container_name: mongodb_palchevskyi
    image: mongo:latest
    volumes:
      - ./dbdata:/data/db
    command: [ --auth ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

networks:
  my-network:
    driver: bridge
volumes:
  dbdata: