version: "3"
# Версия синтаксиса Docker Compose, используемая в этом файле.

services:
  db:
    # Определение контейнера для MySQL базы данных.
    container_name: db
    # Имя контейнера.

    image: mysql:latest
    # Используемый образ Docker для MySQL, в данном случае - последней версии.

    ports:
      - "3306:3306"
    # Проброс портов: 3306 на хосте (левая сторона) и 3306 в контейнере (правая сторона).
    # Это позволяет подключаться к базе данных с хоста.

    environment:
      MYSQL_ROOT_PASSWORD: root
    # Устанавливаем переменную окружения с паролем для root пользователя MySQL.

  phpmyadmin:
    # Определение контейнера для PhpMyAdmin.
    image: phpmyadmin/phpmyadmin
    # Используемый образ Docker для PhpMyAdmin.

    container_name: phpmyadmin
    # Имя контейнера.

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    # Устанавливаем переменные окружения для PhpMyAdmin.
    # PMA_ARBITRARY=1 позволяет вводить произвольное имя хоста для подключения.
    # PMA_HOST=db указывает, что хостом для подключения является контейнер с MySQL (имя "db").

    ports:
      - "8081:80"
    # Проброс портов: 8081 на хосте (левая сторона) и 80 в контейнере (правая сторона).
    # Это позволяет обращаться к PhpMyAdmin через порт 8081 на хосте.
